# Generated by Django 5.1 on 2025-12-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='pledge_type',
            field=models.CharField(choices=[('MONEY', 'Money'), ('SKILL', 'Skill')], default='MONEY', max_length=10),
        ),
        migrations.AddField(
            model_name='pledge',
            name='skill_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
