# Generated by Django 5.1 on 2025-12-04 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('fundraisers', '0003_pledge_hours_pledge_pledge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundraisers', to='buildings.building'),
        ),
    ]
