# Generated by Django 5.1 on 2025-12-04 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_building_photo'),
        ('fundraisers', '0004_fundraiser_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraisers', to='buildings.building'),
        ),
    ]
