# Generated by Django 5.1 on 2025-12-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
