# Generated by Django 5.1 on 2025-12-05 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_building_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildingMembership',
        ),
    ]
